import Head from "next/head";
import Image from "next/image";
import Banner from "../components/Banner";
import Whyus from "../components/Whyus";
import Arrivals from "../components/Arrivals";
import Subscribe from "../components/Subscribe";
import Testimonial from "../components/Testimonial";
import TempProduct from "../components/TempProduct";
import AllProducts from "../components/Products";
// import { BrowserRouter } from "react-router-dom";

export default function Home() {
  return (
    <div>
      <Head>
        <title>CodesWear.com - wear the code</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner />
      <Whyus />
      <Arrivals />
      <TempProduct />
      {/* <AllProducts />       */}
      {/* <BrowserRouter> */}
        <Testimonial />
      {/* </BrowserRouter> */}
      <Subscribe />
      
     </div>
  );
}

// http://localhost:3000/api/addproducts
// [{
//   "title": "shirt",
//   "slug": "hii",
//   "desc": "just image",
//   "img": "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.wired.com%2Fstory%2Fgoogle-wants-to-kill-the-url%2F&psig=AOvVaw0RsL7UjawztjMqaGnRMWSe&ust=1682714422055000&source=images&cd=vfe&ved=0CA4QjRxqFwoTCPjx2-GWzP4CFQAAAAAdAAAAABAD",
//   "category": "hoddies",
//   "size": "XL",
//   "color": "Red",
//   "price": 45,
//   "availableQty": 78
//   }]
